# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import moving_target_pb2 as moving__target__pb2


class LauncherCommandServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendCommand = channel.unary_unary(
        '/launcher_command.LauncherCommandService/SendCommand',
        request_serializer=moving__target__pb2.LauncherCommandRequest.SerializeToString,
        response_deserializer=moving__target__pb2.LauncherCommandReply.FromString,
        )


class LauncherCommandServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LauncherCommandServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendCommand,
          request_deserializer=moving__target__pb2.LauncherCommandRequest.FromString,
          response_serializer=moving__target__pb2.LauncherCommandReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'launcher_command.LauncherCommandService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
