# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import naval_bridge_pb2 as naval__bridge__pb2


class NavalBridgeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendGunRateCommand = channel.unary_unary(
        '/naval_bridge.NavalBridgeService/SendGunRateCommand',
        request_serializer=naval__bridge__pb2.GunRateCommandRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.CommandReply.FromString,
        )
    self.SendFireCommand = channel.unary_unary(
        '/naval_bridge.NavalBridgeService/SendFireCommand',
        request_serializer=naval__bridge__pb2.FireCommandRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.CommandReply.FromString,
        )
    self.StreamTargetPosition = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamTargetPosition',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.TargetPositionInfo.FromString,
        )
    self.StreamGunInfo = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamGunInfo',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.GunInfo.FromString,
        )
    self.StreamGunStatus = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamGunStatus',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.GunStatusInfo.FromString,
        )
    self.StreamPlatformPosition = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamPlatformPosition',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.PlatformPositionInfo.FromString,
        )
    self.StreamPlatformVelocity = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamPlatformVelocity',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.PlatformVelocityInfo.FromString,
        )
    self.StreamStabilizationData = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamStabilizationData',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.StabilizationData.FromString,
        )
    self.StreamPlatformStatus = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamPlatformStatus',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.PlatformStatusInfo.FromString,
        )
    self.StreamHeartbeat = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamHeartbeat',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.Heartbeat.FromString,
        )


class NavalBridgeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendGunRateCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendFireCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamTargetPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamGunInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamGunStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamPlatformPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamPlatformVelocity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamStabilizationData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamPlatformStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamHeartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NavalBridgeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendGunRateCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendGunRateCommand,
          request_deserializer=naval__bridge__pb2.GunRateCommandRequest.FromString,
          response_serializer=naval__bridge__pb2.CommandReply.SerializeToString,
      ),
      'SendFireCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendFireCommand,
          request_deserializer=naval__bridge__pb2.FireCommandRequest.FromString,
          response_serializer=naval__bridge__pb2.CommandReply.SerializeToString,
      ),
      'StreamTargetPosition': grpc.unary_stream_rpc_method_handler(
          servicer.StreamTargetPosition,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.TargetPositionInfo.SerializeToString,
      ),
      'StreamGunInfo': grpc.unary_stream_rpc_method_handler(
          servicer.StreamGunInfo,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.GunInfo.SerializeToString,
      ),
      'StreamGunStatus': grpc.unary_stream_rpc_method_handler(
          servicer.StreamGunStatus,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.GunStatusInfo.SerializeToString,
      ),
      'StreamPlatformPosition': grpc.unary_stream_rpc_method_handler(
          servicer.StreamPlatformPosition,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.PlatformPositionInfo.SerializeToString,
      ),
      'StreamPlatformVelocity': grpc.unary_stream_rpc_method_handler(
          servicer.StreamPlatformVelocity,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.PlatformVelocityInfo.SerializeToString,
      ),
      'StreamStabilizationData': grpc.unary_stream_rpc_method_handler(
          servicer.StreamStabilizationData,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.StabilizationData.SerializeToString,
      ),
      'StreamPlatformStatus': grpc.unary_stream_rpc_method_handler(
          servicer.StreamPlatformStatus,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.PlatformStatusInfo.SerializeToString,
      ),
      'StreamHeartbeat': grpc.unary_stream_rpc_method_handler(
          servicer.StreamHeartbeat,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.Heartbeat.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'naval_bridge.NavalBridgeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
