# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc_ros_bridge import target_pb2 as target__pb2

class TargetServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendTarget = channel.unary_unary(
        '/target.TargetService/SendTarget',
        request_serializer=target__pb2.TargetRequest.SerializeToString,
        response_deserializer=target__pb2.TargetResponse.FromString,
        )


class TargetServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendTarget(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TargetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendTarget': grpc.unary_unary_rpc_method_handler(
          servicer.SendTarget,
          request_deserializer=target__pb2.TargetRequest.FromString,
          response_serializer=target__pb2.TargetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'target.TargetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
