kafka.bootstrap.servers=localhost:9092
kafka.command.topic=launcher.commands
kafka.status.topic=launcher.status
kafka.telemetry.topic=launcher.telemetry
kafka.reports.topic=launcher.reports
kafka.status.group.id=launcher-frontend-status
kafka.reports.group.id=launcher-frontend-reports
