# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moving_target.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moving_target.proto',
  package='launcher_command',
  syntax='proto3',
  serialized_pb=_b('\n\x13moving_target.proto\x12\x10launcher_command\"_\n\x16LauncherCommandRequest\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x16\n\x0eleft_motor_rpm\x18\x03 \x01(\x01\x12\x17\n\x0fright_motor_rpm\x18\x04 \x01(\x01\"9\n\x14LauncherCommandReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2y\n\x16LauncherCommandService\x12_\n\x0bSendCommand\x12(.launcher_command.LauncherCommandRequest\x1a&.launcher_command.LauncherCommandReplyb\x06proto3')
)




_LAUNCHERCOMMANDREQUEST = _descriptor.Descriptor(
  name='LauncherCommandRequest',
  full_name='launcher_command.LauncherCommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='launcher_command.LauncherCommandRequest.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='launcher_command.LauncherCommandRequest.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_motor_rpm', full_name='launcher_command.LauncherCommandRequest.left_motor_rpm', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_motor_rpm', full_name='launcher_command.LauncherCommandRequest.right_motor_rpm', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=136,
)


_LAUNCHERCOMMANDREPLY = _descriptor.Descriptor(
  name='LauncherCommandReply',
  full_name='launcher_command.LauncherCommandReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accepted', full_name='launcher_command.LauncherCommandReply.accepted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='launcher_command.LauncherCommandReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['LauncherCommandRequest'] = _LAUNCHERCOMMANDREQUEST
DESCRIPTOR.message_types_by_name['LauncherCommandReply'] = _LAUNCHERCOMMANDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LauncherCommandRequest = _reflection.GeneratedProtocolMessageType('LauncherCommandRequest', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHERCOMMANDREQUEST,
  __module__ = 'moving_target_pb2'
  # @@protoc_insertion_point(class_scope:launcher_command.LauncherCommandRequest)
  ))
_sym_db.RegisterMessage(LauncherCommandRequest)

LauncherCommandReply = _reflection.GeneratedProtocolMessageType('LauncherCommandReply', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHERCOMMANDREPLY,
  __module__ = 'moving_target_pb2'
  # @@protoc_insertion_point(class_scope:launcher_command.LauncherCommandReply)
  ))
_sym_db.RegisterMessage(LauncherCommandReply)



_LAUNCHERCOMMANDSERVICE = _descriptor.ServiceDescriptor(
  name='LauncherCommandService',
  full_name='launcher_command.LauncherCommandService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=197,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendCommand',
    full_name='launcher_command.LauncherCommandService.SendCommand',
    index=0,
    containing_service=None,
    input_type=_LAUNCHERCOMMANDREQUEST,
    output_type=_LAUNCHERCOMMANDREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAUNCHERCOMMANDSERVICE)

DESCRIPTOR.services_by_name['LauncherCommandService'] = _LAUNCHERCOMMANDSERVICE

# @@protoc_insertion_point(module_scope)
