# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import naval_bridge_pb2 as naval__bridge__pb2


class NavalBridgeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendGunRateCommand = channel.unary_unary(
        '/naval_bridge.NavalBridgeService/SendGunRateCommand',
        request_serializer=naval__bridge__pb2.GunRateCommandRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.CommandReply.FromString,
        )
    self.SendTargetInfo = channel.unary_unary(
        '/naval_bridge.NavalBridgeService/SendTargetInfo',
        request_serializer=naval__bridge__pb2.TargetInfoRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.CommandReply.FromString,
        )
    self.StreamSimulationPackets = channel.unary_stream(
        '/naval_bridge.NavalBridgeService/StreamSimulationPackets',
        request_serializer=naval__bridge__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=naval__bridge__pb2.SimulationPacket.FromString,
        )


class NavalBridgeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendGunRateCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTargetInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamSimulationPackets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NavalBridgeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendGunRateCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendGunRateCommand,
          request_deserializer=naval__bridge__pb2.GunRateCommandRequest.FromString,
          response_serializer=naval__bridge__pb2.CommandReply.SerializeToString,
      ),
      'SendTargetInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SendTargetInfo,
          request_deserializer=naval__bridge__pb2.TargetInfoRequest.FromString,
          response_serializer=naval__bridge__pb2.CommandReply.SerializeToString,
      ),
      'StreamSimulationPackets': grpc.unary_stream_rpc_method_handler(
          servicer.StreamSimulationPackets,
          request_deserializer=naval__bridge__pb2.SubscribeRequest.FromString,
          response_serializer=naval__bridge__pb2.SimulationPacket.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'naval_bridge.NavalBridgeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
