# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: target.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='target.proto',
  package='target',
  syntax='proto3',
  serialized_pb=_b('\n\x0ctarget.proto\x12\x06target\"%\n\rTargetRequest\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"2\n\x0eTargetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2L\n\rTargetService\x12;\n\nSendTarget\x12\x15.target.TargetRequest\x1a\x16.target.TargetResponseb\x06proto3')
)




_TARGETREQUEST = _descriptor.Descriptor(
  name='TargetRequest',
  full_name='target.TargetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='target.TargetRequest.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='target.TargetRequest.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=61,
)


_TARGETRESPONSE = _descriptor.Descriptor(
  name='TargetResponse',
  full_name='target.TargetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='target.TargetResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='target.TargetResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['TargetRequest'] = _TARGETREQUEST
DESCRIPTOR.message_types_by_name['TargetResponse'] = _TARGETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetRequest = _reflection.GeneratedProtocolMessageType('TargetRequest', (_message.Message,), dict(
  DESCRIPTOR = _TARGETREQUEST,
  __module__ = 'target_pb2'
  # @@protoc_insertion_point(class_scope:target.TargetRequest)
  ))
_sym_db.RegisterMessage(TargetRequest)

TargetResponse = _reflection.GeneratedProtocolMessageType('TargetResponse', (_message.Message,), dict(
  DESCRIPTOR = _TARGETRESPONSE,
  __module__ = 'target_pb2'
  # @@protoc_insertion_point(class_scope:target.TargetResponse)
  ))
_sym_db.RegisterMessage(TargetResponse)



_TARGETSERVICE = _descriptor.ServiceDescriptor(
  name='TargetService',
  full_name='target.TargetService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=115,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendTarget',
    full_name='target.TargetService.SendTarget',
    index=0,
    containing_service=None,
    input_type=_TARGETREQUEST,
    output_type=_TARGETRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TARGETSERVICE)

DESCRIPTOR.services_by_name['TargetService'] = _TARGETSERVICE

# @@protoc_insertion_point(module_scope)
